services:
    firstService:
        port: 9080
        base_url: http://localhost
        endpoints:
            get:
                - /user
                - /item
                - /testing
            put:
                - /user/*/*/fdf
                - /item/*/*
            delete:
                - /user/
                - /item/
            post: 
                - /user/create
                - /item/create
        secret_key: mainServiceIsRestrictedOnly
    secondService:
        port: 9081
        base_url: http://localhost
        endpoints:
            get:
                - /hello
                - /user/*
            put:
                - /user/hello
            delete:
                - /user/delete/*
            post: 
                - /user/create
        secret_key: mainServiceIsRestrictedOnly